# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPtAyQbUExVHP-Uijmf9RJOmw7acJV6P
"""

import requests
import json

def get_weather_data(location):
    api_key = "apifgdse45t"  
    base_url = f"http://api.openweathermap.org/data/2.5/weather?q={location}&appid={api_key}"
    
    response = requests.get(base_url)
    data = response.json()
    
    return data

def display_weather_info(weather_data):
    main_weather = weather_data['weather'][0]['main']
    description = weather_data['weather'][0]['description']
    temp = weather_data['main']['temp']
    humidity = weather_data['main']['humidity']
    wind_speed = weather_data['wind']['speed']
    
    print(f"Weather: {main_weather} ({description})")
    print(f"Temperature: {temp}°C")
    print(f"Humidity: {humidity}%")
    print(f"Wind Speed: {wind_speed} m/s")

# Example usage
location = input("Enter a location: ")
weather_data = get_weather_data(location)

if weather_data['cod'] == '404':
    print("Location not found.")
else:
    display_weather_info(weather_data)